### ISSUE TITLE
Fails to build with stack lts-20.2 snapshot [GHC 9.2.5]

### ISSUE THREAD

**Issue by arjunkathuria** [phadej/singleton-bool#22]
Hi,

i am trying to upgrade a project that makes use of this package to latest stack lts and it seems to fail to build. 

it seems it's an indirect dependency of some sorts if that helps?

i get this error log

```
singleton-bool                              > Preprocessing library for singleton-bool-0.1.6..                                                                    
singleton-bool                              > Building library for singleton-bool-0.1.6..                                                                         
singleton-bool                              > [1 of 1] Compiling Data.Singletons.Bool                                                                             
direct-sqlite                               > Registering library for direct-sqlite-2.3.26..                                                                      
singleton-bool                              >                                                                                                                     
singleton-bool                              > /tmp/stack-9f55c734a91504b3/singleton-bool-0.1.6/src/Data/Singletons/Bool.hs:156:18: error:                         
singleton-bool                              >     • Couldn't match kind ‘Bool’ with ‘*’                                                                           
singleton-bool                              >       Expected kind ‘* -> *’, but ‘SBool’ has kind ‘Bool -> *’                                                      
singleton-bool                              >     • In the first argument of ‘GNFData’, namely ‘SBool’                                                            
singleton-bool                              >       In the instance declaration for ‘GNFData SBool’                                                               
singleton-bool                              >     |                                                                                                               
singleton-bool                              > 156 | instance GNFData SBool where                                                                                  
singleton-bool                              >     |                  ^^^^^ 
```

The tested with section doesn't mention GHC 9.2.5, (it only goes  up to 9.2.4), thus opening this issue. 

Thanks.

**Comment by phadej** [comment]
I cannot reproduce. This looks like you are using older version of `some` with not-yet `PolyKinds` `GNFData`, but you claim to use `lts-20.2` which has recent enough `some`.

- Are you using `allow-newer`?
- What is the exact build plan? (IIRC `stack ls dependencies`?)

**Comment by arjunkathuria** [comment]
hi @phadej ,

Thanks for getting back this promptly.

* yes, i am allowing newer with `allow-newer`

This project was on a relatively old snapshot with added (and pinned) deps to accommodate as the project grew but the snapshot remained the same.

i found it had pinned a version of `some` to an older version, which seemed to be just the issue as you mentioned. I just couldn't pin-point that it was the `some` package that was breaking this.

Thanks a lot again.

Closing this as it seems to clearly be an issue on the project's side and not with the library itself.
